uncommented several codecov steps in ci

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -1,5 +1,10 @@
 name: CI
 
+permissions:
+  pull-requests: write
+  contents: read
+  issues: write
+
 on:
   push:
     branches:
@@ -130,18 +135,23 @@ jobs:
           uv pip install .[dev] --no-cache-dir
         shell: pwsh
 
-      # - name: Show dependencies
-      #   run: |
-      #     if [[ "${{ runner.os }}" == "Windows" ]]; then
-      #       .venv\Scripts\activate
-      #     else
-      #       source .venv/bin/activate
-      #     fi
-      #     uv pip list
+      - name: Show dependencies on Windows
+        if: runner.os == 'Windows'
+        run: |
+          .\.venv\Scripts\Activate.ps1
+          uv pip list
+        shell: pwsh
 
-      # - name: Show available branches
-      #   run: |
-      #     git branch -a
+      - name: Show dependencies on Linux and macOS
+        if: runner.os != 'Windows'
+        run: |
+          source .venv/bin/activate
+          uv pip list
+        shell: bash
+
+      - name: Show available branches
+        run: |
+          git branch -a
 
       - name: Run tests on Linux and macOS
         if: runner.os != 'Windows'
@@ -213,27 +223,23 @@ jobs:
         shell: pwsh
 
 
-      # - name: Show dependencies
-      #   run: |
-      #     if [[ "${{ runner.os }}" == "Windows" ]]; then
-      #       .venv\Scripts\activate
-      #     else
-      #       source .venv/bin/activate
-      #     fi
-      #     uv pip list
+      - name: Show dependencies on Windows
+        if: runner.os == 'Windows' && matrix.python-version != '3.12'
+        run: |
+          .\.venv\Scripts\Activate.ps1
+          uv pip list
+        shell: pwsh
 
-      # - name: Show dependencies
-      #   run: |
-      #     if [[ "${{ runner.os }}" == "Windows" ]]; then
-      #       .venv\Scripts\activate
-      #     else
-      #       source .venv/bin/activate
-      #     fi
-      #     uv pip list
+      - name: Show dependencies on Linux and macOS
+        if: runner.os != 'Windows'
+        run: |
+          source .venv/bin/activate
+          uv pip list
+        shell: bash
 
-      # - name: Show available branches
-      #   run: |
-      #      git branch -a
+      - name: Show available branches
+        run: |
+          git branch -a
 
       - name: Run tests on Linux and macOS
         if: runner.os != 'Windows'
@@ -250,42 +256,62 @@ jobs:
           python -m pytest src/ tests/ -vv
         shell: pwsh
 
+      # - name: Publish code coverage
+      #   if: runner.os != 'Windows' || matrix.python-version != '3.12'
+      #   uses: codecov/codecov-action@v4
+      #   with:
+      #     token: ${{secrets.CODECOV_TOKEN}}  # Use the secret token
+      #     fail_ci_if_error: true
+      #     verbose: true
+
+      - name: Find Pull Request
+        id: finder
+        uses: actions/github-script@v7
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          script: |
+            console.log("Event payload:", JSON.stringify(github.event, null, 2));
+            const pr = github.event.pull_request || (github.event.issue ? github.event.issue.pull_request : null);
+            if (pr) {
+              console.log("Found PR number:", pr.number);
+              core.setOutput('pr', pr.number);
+            } else {
+              core.setFailed('No pull request found.');
+            }
+
+      # Add coverage report to PR
+      - name: Add coverage report to PR
+        uses: marocchino/sticky-pull-request-comment@v2.9.0
+        if: always()
+        with:
+          number: ${{ steps.finder.outputs.pr }}
+          recreate: true
+          path: coverage_concise.md
+
+      # Upload coverage report
+      - name: Upload coverage report
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage
+          path: coverage.md
+
+
       - name: Publish code coverage
         if: runner.os != 'Windows' || matrix.python-version != '3.12'
         uses: codecov/codecov-action@v4
+        with:
+          token: ${{secrets.CODECOV_TOKEN}}  # Use the secret token
+          fail_ci_if_error: true
+          verbose: true
 
-
-    # Add coverage report to PR
-    #- name: Add coverage report to PR
-    #  uses: marocchino/sticky-pull-request-comment@v2
-    #  if: always()
-    #  with:
-    #    number: ${{ steps.finder.outputs.pr }}
-    #    recreate: true
-    #    path: coverage_concise.md
-
-    # Upload coverage report
-    #- name: Upload coverage report
-    #  uses: actions/upload-artifact@v4
-    #  with:
-    #    name: coverage
-    #    path: coverage.md
-
-    # Publish coverage report to PR
-    #- name: Publish coverage to PR
-    #  uses: codecov/codecov-action@v3
-    #  with:
-    #    token: ${{ secrets.CODECOV_TOKEN }}
-    #    fail_ci_if_error: true
-    #    verbose: true
-
-  # commitlint:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         fetch-depth: 0
-  #     - uses: wagoid/commitlint-github-action@v4
+  commitlint:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - uses: wagoid/commitlint-github-action@v6
 
 
   docs:
